
// This file is autogenerated.

package translators


import(
"github.com/go-playground/locales"
"github.com/go-playground/locales/af"
"github.com/go-playground/locales/af_NA"
"github.com/go-playground/locales/af_ZA"
"github.com/go-playground/locales/agq"
"github.com/go-playground/locales/agq_CM"
"github.com/go-playground/locales/ak"
"github.com/go-playground/locales/ak_GH"
"github.com/go-playground/locales/am"
"github.com/go-playground/locales/am_ET"
"github.com/go-playground/locales/ar"
"github.com/go-playground/locales/ar_001"
"github.com/go-playground/locales/ar_AE"
"github.com/go-playground/locales/ar_BH"
"github.com/go-playground/locales/ar_DJ"
"github.com/go-playground/locales/ar_DZ"
"github.com/go-playground/locales/ar_EG"
"github.com/go-playground/locales/ar_EH"
"github.com/go-playground/locales/ar_ER"
"github.com/go-playground/locales/ar_IL"
"github.com/go-playground/locales/ar_IQ"
"github.com/go-playground/locales/ar_JO"
"github.com/go-playground/locales/ar_KM"
"github.com/go-playground/locales/ar_KW"
"github.com/go-playground/locales/ar_LB"
"github.com/go-playground/locales/ar_LY"
"github.com/go-playground/locales/ar_MA"
"github.com/go-playground/locales/ar_MR"
"github.com/go-playground/locales/ar_OM"
"github.com/go-playground/locales/ar_PS"
"github.com/go-playground/locales/ar_QA"
"github.com/go-playground/locales/ar_SA"
"github.com/go-playground/locales/ar_SD"
"github.com/go-playground/locales/ar_SO"
"github.com/go-playground/locales/ar_SS"
"github.com/go-playground/locales/ar_SY"
"github.com/go-playground/locales/ar_TD"
"github.com/go-playground/locales/ar_TN"
"github.com/go-playground/locales/ar_YE"
"github.com/go-playground/locales/as"
"github.com/go-playground/locales/as_IN"
"github.com/go-playground/locales/asa"
"github.com/go-playground/locales/asa_TZ"
"github.com/go-playground/locales/ast"
"github.com/go-playground/locales/ast_ES"
"github.com/go-playground/locales/az"
"github.com/go-playground/locales/az_Cyrl"
"github.com/go-playground/locales/az_Cyrl_AZ"
"github.com/go-playground/locales/az_Latn"
"github.com/go-playground/locales/az_Latn_AZ"
"github.com/go-playground/locales/bas"
"github.com/go-playground/locales/bas_CM"
"github.com/go-playground/locales/be"
"github.com/go-playground/locales/be_BY"
"github.com/go-playground/locales/bem"
"github.com/go-playground/locales/bem_ZM"
"github.com/go-playground/locales/bez"
"github.com/go-playground/locales/bez_TZ"
"github.com/go-playground/locales/bg"
"github.com/go-playground/locales/bg_BG"
"github.com/go-playground/locales/bm"
"github.com/go-playground/locales/bm_ML"
"github.com/go-playground/locales/bn"
"github.com/go-playground/locales/bn_BD"
"github.com/go-playground/locales/bn_IN"
"github.com/go-playground/locales/bo"
"github.com/go-playground/locales/bo_CN"
"github.com/go-playground/locales/bo_IN"
"github.com/go-playground/locales/br"
"github.com/go-playground/locales/br_FR"
"github.com/go-playground/locales/brx"
"github.com/go-playground/locales/brx_IN"
"github.com/go-playground/locales/bs"
"github.com/go-playground/locales/bs_Cyrl"
"github.com/go-playground/locales/bs_Cyrl_BA"
"github.com/go-playground/locales/bs_Latn"
"github.com/go-playground/locales/bs_Latn_BA"
"github.com/go-playground/locales/ca"
"github.com/go-playground/locales/ca_AD"
"github.com/go-playground/locales/ca_ES"
"github.com/go-playground/locales/ca_ES_VALENCIA"
"github.com/go-playground/locales/ca_FR"
"github.com/go-playground/locales/ca_IT"
"github.com/go-playground/locales/ccp"
"github.com/go-playground/locales/ccp_BD"
"github.com/go-playground/locales/ccp_IN"
"github.com/go-playground/locales/ce"
"github.com/go-playground/locales/ce_RU"
"github.com/go-playground/locales/cgg"
"github.com/go-playground/locales/cgg_UG"
"github.com/go-playground/locales/chr"
"github.com/go-playground/locales/chr_US"
"github.com/go-playground/locales/ckb"
"github.com/go-playground/locales/ckb_IQ"
"github.com/go-playground/locales/ckb_IR"
"github.com/go-playground/locales/cs"
"github.com/go-playground/locales/cs_CZ"
"github.com/go-playground/locales/cu"
"github.com/go-playground/locales/cu_RU"
"github.com/go-playground/locales/cy"
"github.com/go-playground/locales/cy_GB"
"github.com/go-playground/locales/da"
"github.com/go-playground/locales/da_DK"
"github.com/go-playground/locales/da_GL"
"github.com/go-playground/locales/dav"
"github.com/go-playground/locales/dav_KE"
"github.com/go-playground/locales/de"
"github.com/go-playground/locales/de_AT"
"github.com/go-playground/locales/de_BE"
"github.com/go-playground/locales/de_CH"
"github.com/go-playground/locales/de_DE"
"github.com/go-playground/locales/de_IT"
"github.com/go-playground/locales/de_LI"
"github.com/go-playground/locales/de_LU"
"github.com/go-playground/locales/dje"
"github.com/go-playground/locales/dje_NE"
"github.com/go-playground/locales/dsb"
"github.com/go-playground/locales/dsb_DE"
"github.com/go-playground/locales/dua"
"github.com/go-playground/locales/dua_CM"
"github.com/go-playground/locales/dyo"
"github.com/go-playground/locales/dyo_SN"
"github.com/go-playground/locales/dz"
"github.com/go-playground/locales/dz_BT"
"github.com/go-playground/locales/ebu"
"github.com/go-playground/locales/ebu_KE"
"github.com/go-playground/locales/ee"
"github.com/go-playground/locales/ee_GH"
"github.com/go-playground/locales/ee_TG"
"github.com/go-playground/locales/el"
"github.com/go-playground/locales/el_CY"
"github.com/go-playground/locales/el_GR"
"github.com/go-playground/locales/en"
"github.com/go-playground/locales/en_001"
"github.com/go-playground/locales/en_150"
"github.com/go-playground/locales/en_AG"
"github.com/go-playground/locales/en_AI"
"github.com/go-playground/locales/en_AS"
"github.com/go-playground/locales/en_AT"
"github.com/go-playground/locales/en_AU"
"github.com/go-playground/locales/en_BB"
"github.com/go-playground/locales/en_BE"
"github.com/go-playground/locales/en_BI"
"github.com/go-playground/locales/en_BM"
"github.com/go-playground/locales/en_BS"
"github.com/go-playground/locales/en_BW"
"github.com/go-playground/locales/en_BZ"
"github.com/go-playground/locales/en_CA"
"github.com/go-playground/locales/en_CC"
"github.com/go-playground/locales/en_CH"
"github.com/go-playground/locales/en_CK"
"github.com/go-playground/locales/en_CM"
"github.com/go-playground/locales/en_CX"
"github.com/go-playground/locales/en_CY"
"github.com/go-playground/locales/en_DE"
"github.com/go-playground/locales/en_DG"
"github.com/go-playground/locales/en_DK"
"github.com/go-playground/locales/en_DM"
"github.com/go-playground/locales/en_ER"
"github.com/go-playground/locales/en_FI"
"github.com/go-playground/locales/en_FJ"
"github.com/go-playground/locales/en_FK"
"github.com/go-playground/locales/en_FM"
"github.com/go-playground/locales/en_GB"
"github.com/go-playground/locales/en_GD"
"github.com/go-playground/locales/en_GG"
"github.com/go-playground/locales/en_GH"
"github.com/go-playground/locales/en_GI"
"github.com/go-playground/locales/en_GM"
"github.com/go-playground/locales/en_GU"
"github.com/go-playground/locales/en_GY"
"github.com/go-playground/locales/en_HK"
"github.com/go-playground/locales/en_IE"
"github.com/go-playground/locales/en_IL"
"github.com/go-playground/locales/en_IM"
"github.com/go-playground/locales/en_IN"
"github.com/go-playground/locales/en_IO"
"github.com/go-playground/locales/en_JE"
"github.com/go-playground/locales/en_JM"
"github.com/go-playground/locales/en_KE"
"github.com/go-playground/locales/en_KI"
"github.com/go-playground/locales/en_KN"
"github.com/go-playground/locales/en_KY"
"github.com/go-playground/locales/en_LC"
"github.com/go-playground/locales/en_LR"
"github.com/go-playground/locales/en_LS"
"github.com/go-playground/locales/en_MG"
"github.com/go-playground/locales/en_MH"
"github.com/go-playground/locales/en_MO"
"github.com/go-playground/locales/en_MP"
"github.com/go-playground/locales/en_MS"
"github.com/go-playground/locales/en_MT"
"github.com/go-playground/locales/en_MU"
"github.com/go-playground/locales/en_MW"
"github.com/go-playground/locales/en_MY"
"github.com/go-playground/locales/en_NA"
"github.com/go-playground/locales/en_NF"
"github.com/go-playground/locales/en_NG"
"github.com/go-playground/locales/en_NL"
"github.com/go-playground/locales/en_NR"
"github.com/go-playground/locales/en_NU"
"github.com/go-playground/locales/en_NZ"
"github.com/go-playground/locales/en_PG"
"github.com/go-playground/locales/en_PH"
"github.com/go-playground/locales/en_PK"
"github.com/go-playground/locales/en_PN"
"github.com/go-playground/locales/en_PR"
"github.com/go-playground/locales/en_PW"
"github.com/go-playground/locales/en_RW"
"github.com/go-playground/locales/en_SB"
"github.com/go-playground/locales/en_SC"
"github.com/go-playground/locales/en_SD"
"github.com/go-playground/locales/en_SE"
"github.com/go-playground/locales/en_SG"
"github.com/go-playground/locales/en_SH"
"github.com/go-playground/locales/en_SI"
"github.com/go-playground/locales/en_SL"
"github.com/go-playground/locales/en_SS"
"github.com/go-playground/locales/en_SX"
"github.com/go-playground/locales/en_SZ"
"github.com/go-playground/locales/en_TC"
"github.com/go-playground/locales/en_TK"
"github.com/go-playground/locales/en_TO"
"github.com/go-playground/locales/en_TT"
"github.com/go-playground/locales/en_TV"
"github.com/go-playground/locales/en_TZ"
"github.com/go-playground/locales/en_UG"
"github.com/go-playground/locales/en_UM"
"github.com/go-playground/locales/en_US"
"github.com/go-playground/locales/en_US_POSIX"
"github.com/go-playground/locales/en_VC"
"github.com/go-playground/locales/en_VG"
"github.com/go-playground/locales/en_VI"
"github.com/go-playground/locales/en_VU"
"github.com/go-playground/locales/en_WS"
"github.com/go-playground/locales/en_ZA"
"github.com/go-playground/locales/en_ZM"
"github.com/go-playground/locales/en_ZW"
"github.com/go-playground/locales/eo"
"github.com/go-playground/locales/eo_001"
"github.com/go-playground/locales/es"
"github.com/go-playground/locales/es_419"
"github.com/go-playground/locales/es_AR"
"github.com/go-playground/locales/es_BO"
"github.com/go-playground/locales/es_BR"
"github.com/go-playground/locales/es_BZ"
"github.com/go-playground/locales/es_CL"
"github.com/go-playground/locales/es_CO"
"github.com/go-playground/locales/es_CR"
"github.com/go-playground/locales/es_CU"
"github.com/go-playground/locales/es_DO"
"github.com/go-playground/locales/es_EA"
"github.com/go-playground/locales/es_EC"
"github.com/go-playground/locales/es_ES"
"github.com/go-playground/locales/es_GQ"
"github.com/go-playground/locales/es_GT"
"github.com/go-playground/locales/es_HN"
"github.com/go-playground/locales/es_IC"
"github.com/go-playground/locales/es_MX"
"github.com/go-playground/locales/es_NI"
"github.com/go-playground/locales/es_PA"
"github.com/go-playground/locales/es_PE"
"github.com/go-playground/locales/es_PH"
"github.com/go-playground/locales/es_PR"
"github.com/go-playground/locales/es_PY"
"github.com/go-playground/locales/es_SV"
"github.com/go-playground/locales/es_US"
"github.com/go-playground/locales/es_UY"
"github.com/go-playground/locales/es_VE"
"github.com/go-playground/locales/et"
"github.com/go-playground/locales/et_EE"
"github.com/go-playground/locales/eu"
"github.com/go-playground/locales/eu_ES"
"github.com/go-playground/locales/ewo"
"github.com/go-playground/locales/ewo_CM"
"github.com/go-playground/locales/fa"
"github.com/go-playground/locales/fa_AF"
"github.com/go-playground/locales/fa_IR"
"github.com/go-playground/locales/ff"
"github.com/go-playground/locales/ff_CM"
"github.com/go-playground/locales/ff_GN"
"github.com/go-playground/locales/ff_MR"
"github.com/go-playground/locales/ff_SN"
"github.com/go-playground/locales/fi"
"github.com/go-playground/locales/fi_FI"
"github.com/go-playground/locales/fil"
"github.com/go-playground/locales/fil_PH"
"github.com/go-playground/locales/fo"
"github.com/go-playground/locales/fo_DK"
"github.com/go-playground/locales/fo_FO"
"github.com/go-playground/locales/fr"
"github.com/go-playground/locales/fr_BE"
"github.com/go-playground/locales/fr_BF"
"github.com/go-playground/locales/fr_BI"
"github.com/go-playground/locales/fr_BJ"
"github.com/go-playground/locales/fr_BL"
"github.com/go-playground/locales/fr_CA"
"github.com/go-playground/locales/fr_CD"
"github.com/go-playground/locales/fr_CF"
"github.com/go-playground/locales/fr_CG"
"github.com/go-playground/locales/fr_CH"
"github.com/go-playground/locales/fr_CI"
"github.com/go-playground/locales/fr_CM"
"github.com/go-playground/locales/fr_DJ"
"github.com/go-playground/locales/fr_DZ"
"github.com/go-playground/locales/fr_FR"
"github.com/go-playground/locales/fr_GA"
"github.com/go-playground/locales/fr_GF"
"github.com/go-playground/locales/fr_GN"
"github.com/go-playground/locales/fr_GP"
"github.com/go-playground/locales/fr_GQ"
"github.com/go-playground/locales/fr_HT"
"github.com/go-playground/locales/fr_KM"
"github.com/go-playground/locales/fr_LU"
"github.com/go-playground/locales/fr_MA"
"github.com/go-playground/locales/fr_MC"
"github.com/go-playground/locales/fr_MF"
"github.com/go-playground/locales/fr_MG"
"github.com/go-playground/locales/fr_ML"
"github.com/go-playground/locales/fr_MQ"
"github.com/go-playground/locales/fr_MR"
"github.com/go-playground/locales/fr_MU"
"github.com/go-playground/locales/fr_NC"
"github.com/go-playground/locales/fr_NE"
"github.com/go-playground/locales/fr_PF"
"github.com/go-playground/locales/fr_PM"
"github.com/go-playground/locales/fr_RE"
"github.com/go-playground/locales/fr_RW"
"github.com/go-playground/locales/fr_SC"
"github.com/go-playground/locales/fr_SN"
"github.com/go-playground/locales/fr_SY"
"github.com/go-playground/locales/fr_TD"
"github.com/go-playground/locales/fr_TG"
"github.com/go-playground/locales/fr_TN"
"github.com/go-playground/locales/fr_VU"
"github.com/go-playground/locales/fr_WF"
"github.com/go-playground/locales/fr_YT"
"github.com/go-playground/locales/fur"
"github.com/go-playground/locales/fur_IT"
"github.com/go-playground/locales/fy"
"github.com/go-playground/locales/fy_NL"
"github.com/go-playground/locales/ga"
"github.com/go-playground/locales/ga_IE"
"github.com/go-playground/locales/gd"
"github.com/go-playground/locales/gd_GB"
"github.com/go-playground/locales/gl"
"github.com/go-playground/locales/gl_ES"
"github.com/go-playground/locales/gsw"
"github.com/go-playground/locales/gsw_CH"
"github.com/go-playground/locales/gsw_FR"
"github.com/go-playground/locales/gsw_LI"
"github.com/go-playground/locales/gu"
"github.com/go-playground/locales/gu_IN"
"github.com/go-playground/locales/guz"
"github.com/go-playground/locales/guz_KE"
"github.com/go-playground/locales/gv"
"github.com/go-playground/locales/gv_IM"
"github.com/go-playground/locales/ha"
"github.com/go-playground/locales/ha_GH"
"github.com/go-playground/locales/ha_NE"
"github.com/go-playground/locales/ha_NG"
"github.com/go-playground/locales/haw"
"github.com/go-playground/locales/haw_US"
"github.com/go-playground/locales/he"
"github.com/go-playground/locales/he_IL"
"github.com/go-playground/locales/hi"
"github.com/go-playground/locales/hi_IN"
"github.com/go-playground/locales/hr"
"github.com/go-playground/locales/hr_BA"
"github.com/go-playground/locales/hr_HR"
"github.com/go-playground/locales/hsb"
"github.com/go-playground/locales/hsb_DE"
"github.com/go-playground/locales/hu"
"github.com/go-playground/locales/hu_HU"
"github.com/go-playground/locales/hy"
"github.com/go-playground/locales/hy_AM"
"github.com/go-playground/locales/id"
"github.com/go-playground/locales/id_ID"
"github.com/go-playground/locales/ig"
"github.com/go-playground/locales/ig_NG"
"github.com/go-playground/locales/ii"
"github.com/go-playground/locales/ii_CN"
"github.com/go-playground/locales/is"
"github.com/go-playground/locales/is_IS"
"github.com/go-playground/locales/it"
"github.com/go-playground/locales/it_CH"
"github.com/go-playground/locales/it_IT"
"github.com/go-playground/locales/it_SM"
"github.com/go-playground/locales/it_VA"
"github.com/go-playground/locales/ja"
"github.com/go-playground/locales/ja_JP"
"github.com/go-playground/locales/jgo"
"github.com/go-playground/locales/jgo_CM"
"github.com/go-playground/locales/jmc"
"github.com/go-playground/locales/jmc_TZ"
"github.com/go-playground/locales/ka"
"github.com/go-playground/locales/ka_GE"
"github.com/go-playground/locales/kab"
"github.com/go-playground/locales/kab_DZ"
"github.com/go-playground/locales/kam"
"github.com/go-playground/locales/kam_KE"
"github.com/go-playground/locales/kde"
"github.com/go-playground/locales/kde_TZ"
"github.com/go-playground/locales/kea"
"github.com/go-playground/locales/kea_CV"
"github.com/go-playground/locales/khq"
"github.com/go-playground/locales/khq_ML"
"github.com/go-playground/locales/ki"
"github.com/go-playground/locales/ki_KE"
"github.com/go-playground/locales/kk"
"github.com/go-playground/locales/kk_KZ"
"github.com/go-playground/locales/kkj"
"github.com/go-playground/locales/kkj_CM"
"github.com/go-playground/locales/kl"
"github.com/go-playground/locales/kl_GL"
"github.com/go-playground/locales/kln"
"github.com/go-playground/locales/kln_KE"
"github.com/go-playground/locales/km"
"github.com/go-playground/locales/km_KH"
"github.com/go-playground/locales/kn"
"github.com/go-playground/locales/kn_IN"
"github.com/go-playground/locales/ko"
"github.com/go-playground/locales/ko_KP"
"github.com/go-playground/locales/ko_KR"
"github.com/go-playground/locales/kok"
"github.com/go-playground/locales/kok_IN"
"github.com/go-playground/locales/ks"
"github.com/go-playground/locales/ks_IN"
"github.com/go-playground/locales/ksb"
"github.com/go-playground/locales/ksb_TZ"
"github.com/go-playground/locales/ksf"
"github.com/go-playground/locales/ksf_CM"
"github.com/go-playground/locales/ksh"
"github.com/go-playground/locales/ksh_DE"
"github.com/go-playground/locales/kw"
"github.com/go-playground/locales/kw_GB"
"github.com/go-playground/locales/ky"
"github.com/go-playground/locales/ky_KG"
"github.com/go-playground/locales/lag"
"github.com/go-playground/locales/lag_TZ"
"github.com/go-playground/locales/lb"
"github.com/go-playground/locales/lb_LU"
"github.com/go-playground/locales/lg"
"github.com/go-playground/locales/lg_UG"
"github.com/go-playground/locales/lkt"
"github.com/go-playground/locales/lkt_US"
"github.com/go-playground/locales/ln"
"github.com/go-playground/locales/ln_AO"
"github.com/go-playground/locales/ln_CD"
"github.com/go-playground/locales/ln_CF"
"github.com/go-playground/locales/ln_CG"
"github.com/go-playground/locales/lo"
"github.com/go-playground/locales/lo_LA"
"github.com/go-playground/locales/lrc"
"github.com/go-playground/locales/lrc_IQ"
"github.com/go-playground/locales/lrc_IR"
"github.com/go-playground/locales/lt"
"github.com/go-playground/locales/lt_LT"
"github.com/go-playground/locales/lu"
"github.com/go-playground/locales/lu_CD"
"github.com/go-playground/locales/luo"
"github.com/go-playground/locales/luo_KE"
"github.com/go-playground/locales/luy"
"github.com/go-playground/locales/luy_KE"
"github.com/go-playground/locales/lv"
"github.com/go-playground/locales/lv_LV"
"github.com/go-playground/locales/mas"
"github.com/go-playground/locales/mas_KE"
"github.com/go-playground/locales/mas_TZ"
"github.com/go-playground/locales/mer"
"github.com/go-playground/locales/mer_KE"
"github.com/go-playground/locales/mfe"
"github.com/go-playground/locales/mfe_MU"
"github.com/go-playground/locales/mg"
"github.com/go-playground/locales/mg_MG"
"github.com/go-playground/locales/mgh"
"github.com/go-playground/locales/mgh_MZ"
"github.com/go-playground/locales/mgo"
"github.com/go-playground/locales/mgo_CM"
"github.com/go-playground/locales/mk"
"github.com/go-playground/locales/mk_MK"
"github.com/go-playground/locales/ml"
"github.com/go-playground/locales/ml_IN"
"github.com/go-playground/locales/mn"
"github.com/go-playground/locales/mn_MN"
"github.com/go-playground/locales/mr"
"github.com/go-playground/locales/mr_IN"
"github.com/go-playground/locales/ms"
"github.com/go-playground/locales/ms_BN"
"github.com/go-playground/locales/ms_MY"
"github.com/go-playground/locales/ms_SG"
"github.com/go-playground/locales/mt"
"github.com/go-playground/locales/mt_MT"
"github.com/go-playground/locales/mua"
"github.com/go-playground/locales/mua_CM"
"github.com/go-playground/locales/my"
"github.com/go-playground/locales/my_MM"
"github.com/go-playground/locales/mzn"
"github.com/go-playground/locales/mzn_IR"
"github.com/go-playground/locales/naq"
"github.com/go-playground/locales/naq_NA"
"github.com/go-playground/locales/nb"
"github.com/go-playground/locales/nb_NO"
"github.com/go-playground/locales/nb_SJ"
"github.com/go-playground/locales/nd"
"github.com/go-playground/locales/nd_ZW"
"github.com/go-playground/locales/nds"
"github.com/go-playground/locales/nds_DE"
"github.com/go-playground/locales/nds_NL"
"github.com/go-playground/locales/ne"
"github.com/go-playground/locales/ne_IN"
"github.com/go-playground/locales/ne_NP"
"github.com/go-playground/locales/nl"
"github.com/go-playground/locales/nl_AW"
"github.com/go-playground/locales/nl_BE"
"github.com/go-playground/locales/nl_BQ"
"github.com/go-playground/locales/nl_CW"
"github.com/go-playground/locales/nl_NL"
"github.com/go-playground/locales/nl_SR"
"github.com/go-playground/locales/nl_SX"
"github.com/go-playground/locales/nmg"
"github.com/go-playground/locales/nmg_CM"
"github.com/go-playground/locales/nn"
"github.com/go-playground/locales/nn_NO"
"github.com/go-playground/locales/nnh"
"github.com/go-playground/locales/nnh_CM"
"github.com/go-playground/locales/nus"
"github.com/go-playground/locales/nus_SS"
"github.com/go-playground/locales/nyn"
"github.com/go-playground/locales/nyn_UG"
"github.com/go-playground/locales/om"
"github.com/go-playground/locales/om_ET"
"github.com/go-playground/locales/om_KE"
"github.com/go-playground/locales/or"
"github.com/go-playground/locales/or_IN"
"github.com/go-playground/locales/os"
"github.com/go-playground/locales/os_GE"
"github.com/go-playground/locales/os_RU"
"github.com/go-playground/locales/pa"
"github.com/go-playground/locales/pa_Arab"
"github.com/go-playground/locales/pa_Arab_PK"
"github.com/go-playground/locales/pa_Guru"
"github.com/go-playground/locales/pa_Guru_IN"
"github.com/go-playground/locales/pl"
"github.com/go-playground/locales/pl_PL"
"github.com/go-playground/locales/prg"
"github.com/go-playground/locales/prg_001"
"github.com/go-playground/locales/ps"
"github.com/go-playground/locales/ps_AF"
"github.com/go-playground/locales/pt"
"github.com/go-playground/locales/pt_AO"
"github.com/go-playground/locales/pt_BR"
"github.com/go-playground/locales/pt_CH"
"github.com/go-playground/locales/pt_CV"
"github.com/go-playground/locales/pt_GQ"
"github.com/go-playground/locales/pt_GW"
"github.com/go-playground/locales/pt_LU"
"github.com/go-playground/locales/pt_MO"
"github.com/go-playground/locales/pt_MZ"
"github.com/go-playground/locales/pt_PT"
"github.com/go-playground/locales/pt_ST"
"github.com/go-playground/locales/pt_TL"
"github.com/go-playground/locales/qu"
"github.com/go-playground/locales/qu_BO"
"github.com/go-playground/locales/qu_EC"
"github.com/go-playground/locales/qu_PE"
"github.com/go-playground/locales/rm"
"github.com/go-playground/locales/rm_CH"
"github.com/go-playground/locales/rn"
"github.com/go-playground/locales/rn_BI"
"github.com/go-playground/locales/ro"
"github.com/go-playground/locales/ro_MD"
"github.com/go-playground/locales/ro_RO"
"github.com/go-playground/locales/rof"
"github.com/go-playground/locales/rof_TZ"
"github.com/go-playground/locales/root"
"github.com/go-playground/locales/ru"
"github.com/go-playground/locales/ru_BY"
"github.com/go-playground/locales/ru_KG"
"github.com/go-playground/locales/ru_KZ"
"github.com/go-playground/locales/ru_MD"
"github.com/go-playground/locales/ru_RU"
"github.com/go-playground/locales/ru_UA"
"github.com/go-playground/locales/rw"
"github.com/go-playground/locales/rw_RW"
"github.com/go-playground/locales/rwk"
"github.com/go-playground/locales/rwk_TZ"
"github.com/go-playground/locales/sah"
"github.com/go-playground/locales/sah_RU"
"github.com/go-playground/locales/saq"
"github.com/go-playground/locales/saq_KE"
"github.com/go-playground/locales/sbp"
"github.com/go-playground/locales/sbp_TZ"
"github.com/go-playground/locales/sd"
"github.com/go-playground/locales/sd_PK"
"github.com/go-playground/locales/se"
"github.com/go-playground/locales/se_FI"
"github.com/go-playground/locales/se_NO"
"github.com/go-playground/locales/se_SE"
"github.com/go-playground/locales/seh"
"github.com/go-playground/locales/seh_MZ"
"github.com/go-playground/locales/ses"
"github.com/go-playground/locales/ses_ML"
"github.com/go-playground/locales/sg"
"github.com/go-playground/locales/sg_CF"
"github.com/go-playground/locales/shi"
"github.com/go-playground/locales/shi_Latn"
"github.com/go-playground/locales/shi_Latn_MA"
"github.com/go-playground/locales/shi_Tfng"
"github.com/go-playground/locales/shi_Tfng_MA"
"github.com/go-playground/locales/si"
"github.com/go-playground/locales/si_LK"
"github.com/go-playground/locales/sk"
"github.com/go-playground/locales/sk_SK"
"github.com/go-playground/locales/sl"
"github.com/go-playground/locales/sl_SI"
"github.com/go-playground/locales/smn"
"github.com/go-playground/locales/smn_FI"
"github.com/go-playground/locales/sn"
"github.com/go-playground/locales/sn_ZW"
"github.com/go-playground/locales/so"
"github.com/go-playground/locales/so_DJ"
"github.com/go-playground/locales/so_ET"
"github.com/go-playground/locales/so_KE"
"github.com/go-playground/locales/so_SO"
"github.com/go-playground/locales/sq"
"github.com/go-playground/locales/sq_AL"
"github.com/go-playground/locales/sq_MK"
"github.com/go-playground/locales/sq_XK"
"github.com/go-playground/locales/sr"
"github.com/go-playground/locales/sr_Cyrl"
"github.com/go-playground/locales/sr_Cyrl_BA"
"github.com/go-playground/locales/sr_Cyrl_ME"
"github.com/go-playground/locales/sr_Cyrl_RS"
"github.com/go-playground/locales/sr_Cyrl_XK"
"github.com/go-playground/locales/sr_Latn"
"github.com/go-playground/locales/sr_Latn_BA"
"github.com/go-playground/locales/sr_Latn_ME"
"github.com/go-playground/locales/sr_Latn_RS"
"github.com/go-playground/locales/sr_Latn_XK"
"github.com/go-playground/locales/sv"
"github.com/go-playground/locales/sv_AX"
"github.com/go-playground/locales/sv_FI"
"github.com/go-playground/locales/sv_SE"
"github.com/go-playground/locales/sw"
"github.com/go-playground/locales/sw_CD"
"github.com/go-playground/locales/sw_KE"
"github.com/go-playground/locales/sw_TZ"
"github.com/go-playground/locales/sw_UG"
"github.com/go-playground/locales/ta"
"github.com/go-playground/locales/ta_IN"
"github.com/go-playground/locales/ta_LK"
"github.com/go-playground/locales/ta_MY"
"github.com/go-playground/locales/ta_SG"
"github.com/go-playground/locales/te"
"github.com/go-playground/locales/te_IN"
"github.com/go-playground/locales/teo"
"github.com/go-playground/locales/teo_KE"
"github.com/go-playground/locales/teo_UG"
"github.com/go-playground/locales/tg"
"github.com/go-playground/locales/tg_TJ"
"github.com/go-playground/locales/th"
"github.com/go-playground/locales/th_TH"
"github.com/go-playground/locales/ti"
"github.com/go-playground/locales/ti_ER"
"github.com/go-playground/locales/ti_ET"
"github.com/go-playground/locales/tk"
"github.com/go-playground/locales/tk_TM"
"github.com/go-playground/locales/to"
"github.com/go-playground/locales/to_TO"
"github.com/go-playground/locales/tr"
"github.com/go-playground/locales/tr_CY"
"github.com/go-playground/locales/tr_TR"
"github.com/go-playground/locales/tt"
"github.com/go-playground/locales/tt_RU"
"github.com/go-playground/locales/twq"
"github.com/go-playground/locales/twq_NE"
"github.com/go-playground/locales/tzm"
"github.com/go-playground/locales/tzm_MA"
"github.com/go-playground/locales/ug"
"github.com/go-playground/locales/ug_CN"
"github.com/go-playground/locales/uk"
"github.com/go-playground/locales/uk_UA"
"github.com/go-playground/locales/ur"
"github.com/go-playground/locales/ur_IN"
"github.com/go-playground/locales/ur_PK"
"github.com/go-playground/locales/uz"
"github.com/go-playground/locales/uz_Arab"
"github.com/go-playground/locales/uz_Arab_AF"
"github.com/go-playground/locales/uz_Cyrl"
"github.com/go-playground/locales/uz_Cyrl_UZ"
"github.com/go-playground/locales/uz_Latn"
"github.com/go-playground/locales/uz_Latn_UZ"
"github.com/go-playground/locales/vai"
"github.com/go-playground/locales/vai_Latn"
"github.com/go-playground/locales/vai_Latn_LR"
"github.com/go-playground/locales/vai_Vaii"
"github.com/go-playground/locales/vai_Vaii_LR"
"github.com/go-playground/locales/vi"
"github.com/go-playground/locales/vi_VN"
"github.com/go-playground/locales/vo"
"github.com/go-playground/locales/vo_001"
"github.com/go-playground/locales/vun"
"github.com/go-playground/locales/vun_TZ"
"github.com/go-playground/locales/wae"
"github.com/go-playground/locales/wae_CH"
"github.com/go-playground/locales/wo"
"github.com/go-playground/locales/wo_SN"
"github.com/go-playground/locales/xog"
"github.com/go-playground/locales/xog_UG"
"github.com/go-playground/locales/yav"
"github.com/go-playground/locales/yav_CM"
"github.com/go-playground/locales/yi"
"github.com/go-playground/locales/yi_001"
"github.com/go-playground/locales/yo"
"github.com/go-playground/locales/yo_BJ"
"github.com/go-playground/locales/yo_NG"
"github.com/go-playground/locales/yue"
"github.com/go-playground/locales/yue_HK"
"github.com/go-playground/locales/yue_Hans"
"github.com/go-playground/locales/yue_Hans_CN"
"github.com/go-playground/locales/yue_Hant"
"github.com/go-playground/locales/yue_Hant_HK"
"github.com/go-playground/locales/zgh"
"github.com/go-playground/locales/zgh_MA"
"github.com/go-playground/locales/zh"
"github.com/go-playground/locales/zh_Hans"
"github.com/go-playground/locales/zh_Hans_CN"
"github.com/go-playground/locales/zh_Hans_HK"
"github.com/go-playground/locales/zh_Hans_MO"
"github.com/go-playground/locales/zh_Hans_SG"
"github.com/go-playground/locales/zh_Hant"
"github.com/go-playground/locales/zh_Hant_HK"
"github.com/go-playground/locales/zh_Hant_MO"
"github.com/go-playground/locales/zh_Hant_TW"
"github.com/go-playground/locales/zu"
"github.com/go-playground/locales/zu_ZA"

)

func init() {
translatorFuncs["af"] = func() locales.Translator { return af.New() }
translatorFuncs["af_na"] = func() locales.Translator { return af_NA.New() }
translatorFuncs["af_za"] = func() locales.Translator { return af_ZA.New() }
translatorFuncs["agq"] = func() locales.Translator { return agq.New() }
translatorFuncs["agq_cm"] = func() locales.Translator { return agq_CM.New() }
translatorFuncs["ak"] = func() locales.Translator { return ak.New() }
translatorFuncs["ak_gh"] = func() locales.Translator { return ak_GH.New() }
translatorFuncs["am"] = func() locales.Translator { return am.New() }
translatorFuncs["am_et"] = func() locales.Translator { return am_ET.New() }
translatorFuncs["ar"] = func() locales.Translator { return ar.New() }
translatorFuncs["ar_001"] = func() locales.Translator { return ar_001.New() }
translatorFuncs["ar_ae"] = func() locales.Translator { return ar_AE.New() }
translatorFuncs["ar_bh"] = func() locales.Translator { return ar_BH.New() }
translatorFuncs["ar_dj"] = func() locales.Translator { return ar_DJ.New() }
translatorFuncs["ar_dz"] = func() locales.Translator { return ar_DZ.New() }
translatorFuncs["ar_eg"] = func() locales.Translator { return ar_EG.New() }
translatorFuncs["ar_eh"] = func() locales.Translator { return ar_EH.New() }
translatorFuncs["ar_er"] = func() locales.Translator { return ar_ER.New() }
translatorFuncs["ar_il"] = func() locales.Translator { return ar_IL.New() }
translatorFuncs["ar_iq"] = func() locales.Translator { return ar_IQ.New() }
translatorFuncs["ar_jo"] = func() locales.Translator { return ar_JO.New() }
translatorFuncs["ar_km"] = func() locales.Translator { return ar_KM.New() }
translatorFuncs["ar_kw"] = func() locales.Translator { return ar_KW.New() }
translatorFuncs["ar_lb"] = func() locales.Translator { return ar_LB.New() }
translatorFuncs["ar_ly"] = func() locales.Translator { return ar_LY.New() }
translatorFuncs["ar_ma"] = func() locales.Translator { return ar_MA.New() }
translatorFuncs["ar_mr"] = func() locales.Translator { return ar_MR.New() }
translatorFuncs["ar_om"] = func() locales.Translator { return ar_OM.New() }
translatorFuncs["ar_ps"] = func() locales.Translator { return ar_PS.New() }
translatorFuncs["ar_qa"] = func() locales.Translator { return ar_QA.New() }
translatorFuncs["ar_sa"] = func() locales.Translator { return ar_SA.New() }
translatorFuncs["ar_sd"] = func() locales.Translator { return ar_SD.New() }
translatorFuncs["ar_so"] = func() locales.Translator { return ar_SO.New() }
translatorFuncs["ar_ss"] = func() locales.Translator { return ar_SS.New() }
translatorFuncs["ar_sy"] = func() locales.Translator { return ar_SY.New() }
translatorFuncs["ar_td"] = func() locales.Translator { return ar_TD.New() }
translatorFuncs["ar_tn"] = func() locales.Translator { return ar_TN.New() }
translatorFuncs["ar_ye"] = func() locales.Translator { return ar_YE.New() }
translatorFuncs["as"] = func() locales.Translator { return as.New() }
translatorFuncs["as_in"] = func() locales.Translator { return as_IN.New() }
translatorFuncs["asa"] = func() locales.Translator { return asa.New() }
translatorFuncs["asa_tz"] = func() locales.Translator { return asa_TZ.New() }
translatorFuncs["ast"] = func() locales.Translator { return ast.New() }
translatorFuncs["ast_es"] = func() locales.Translator { return ast_ES.New() }
translatorFuncs["az"] = func() locales.Translator { return az.New() }
translatorFuncs["az_cyrl"] = func() locales.Translator { return az_Cyrl.New() }
translatorFuncs["az_cyrl_az"] = func() locales.Translator { return az_Cyrl_AZ.New() }
translatorFuncs["az_latn"] = func() locales.Translator { return az_Latn.New() }
translatorFuncs["az_latn_az"] = func() locales.Translator { return az_Latn_AZ.New() }
translatorFuncs["bas"] = func() locales.Translator { return bas.New() }
translatorFuncs["bas_cm"] = func() locales.Translator { return bas_CM.New() }
translatorFuncs["be"] = func() locales.Translator { return be.New() }
translatorFuncs["be_by"] = func() locales.Translator { return be_BY.New() }
translatorFuncs["bem"] = func() locales.Translator { return bem.New() }
translatorFuncs["bem_zm"] = func() locales.Translator { return bem_ZM.New() }
translatorFuncs["bez"] = func() locales.Translator { return bez.New() }
translatorFuncs["bez_tz"] = func() locales.Translator { return bez_TZ.New() }
translatorFuncs["bg"] = func() locales.Translator { return bg.New() }
translatorFuncs["bg_bg"] = func() locales.Translator { return bg_BG.New() }
translatorFuncs["bm"] = func() locales.Translator { return bm.New() }
translatorFuncs["bm_ml"] = func() locales.Translator { return bm_ML.New() }
translatorFuncs["bn"] = func() locales.Translator { return bn.New() }
translatorFuncs["bn_bd"] = func() locales.Translator { return bn_BD.New() }
translatorFuncs["bn_in"] = func() locales.Translator { return bn_IN.New() }
translatorFuncs["bo"] = func() locales.Translator { return bo.New() }
translatorFuncs["bo_cn"] = func() locales.Translator { return bo_CN.New() }
translatorFuncs["bo_in"] = func() locales.Translator { return bo_IN.New() }
translatorFuncs["br"] = func() locales.Translator { return br.New() }
translatorFuncs["br_fr"] = func() locales.Translator { return br_FR.New() }
translatorFuncs["brx"] = func() locales.Translator { return brx.New() }
translatorFuncs["brx_in"] = func() locales.Translator { return brx_IN.New() }
translatorFuncs["bs"] = func() locales.Translator { return bs.New() }
translatorFuncs["bs_cyrl"] = func() locales.Translator { return bs_Cyrl.New() }
translatorFuncs["bs_cyrl_ba"] = func() locales.Translator { return bs_Cyrl_BA.New() }
translatorFuncs["bs_latn"] = func() locales.Translator { return bs_Latn.New() }
translatorFuncs["bs_latn_ba"] = func() locales.Translator { return bs_Latn_BA.New() }
translatorFuncs["ca"] = func() locales.Translator { return ca.New() }
translatorFuncs["ca_ad"] = func() locales.Translator { return ca_AD.New() }
translatorFuncs["ca_es"] = func() locales.Translator { return ca_ES.New() }
translatorFuncs["ca_es_valencia"] = func() locales.Translator { return ca_ES_VALENCIA.New() }
translatorFuncs["ca_fr"] = func() locales.Translator { return ca_FR.New() }
translatorFuncs["ca_it"] = func() locales.Translator { return ca_IT.New() }
translatorFuncs["ccp"] = func() locales.Translator { return ccp.New() }
translatorFuncs["ccp_bd"] = func() locales.Translator { return ccp_BD.New() }
translatorFuncs["ccp_in"] = func() locales.Translator { return ccp_IN.New() }
translatorFuncs["ce"] = func() locales.Translator { return ce.New() }
translatorFuncs["ce_ru"] = func() locales.Translator { return ce_RU.New() }
translatorFuncs["cgg"] = func() locales.Translator { return cgg.New() }
translatorFuncs["cgg_ug"] = func() locales.Translator { return cgg_UG.New() }
translatorFuncs["chr"] = func() locales.Translator { return chr.New() }
translatorFuncs["chr_us"] = func() locales.Translator { return chr_US.New() }
translatorFuncs["ckb"] = func() locales.Translator { return ckb.New() }
translatorFuncs["ckb_iq"] = func() locales.Translator { return ckb_IQ.New() }
translatorFuncs["ckb_ir"] = func() locales.Translator { return ckb_IR.New() }
translatorFuncs["cs"] = func() locales.Translator { return cs.New() }
translatorFuncs["cs_cz"] = func() locales.Translator { return cs_CZ.New() }
translatorFuncs["cu"] = func() locales.Translator { return cu.New() }
translatorFuncs["cu_ru"] = func() locales.Translator { return cu_RU.New() }
translatorFuncs["cy"] = func() locales.Translator { return cy.New() }
translatorFuncs["cy_gb"] = func() locales.Translator { return cy_GB.New() }
translatorFuncs["da"] = func() locales.Translator { return da.New() }
translatorFuncs["da_dk"] = func() locales.Translator { return da_DK.New() }
translatorFuncs["da_gl"] = func() locales.Translator { return da_GL.New() }
translatorFuncs["dav"] = func() locales.Translator { return dav.New() }
translatorFuncs["dav_ke"] = func() locales.Translator { return dav_KE.New() }
translatorFuncs["de"] = func() locales.Translator { return de.New() }
translatorFuncs["de_at"] = func() locales.Translator { return de_AT.New() }
translatorFuncs["de_be"] = func() locales.Translator { return de_BE.New() }
translatorFuncs["de_ch"] = func() locales.Translator { return de_CH.New() }
translatorFuncs["de_de"] = func() locales.Translator { return de_DE.New() }
translatorFuncs["de_it"] = func() locales.Translator { return de_IT.New() }
translatorFuncs["de_li"] = func() locales.Translator { return de_LI.New() }
translatorFuncs["de_lu"] = func() locales.Translator { return de_LU.New() }
translatorFuncs["dje"] = func() locales.Translator { return dje.New() }
translatorFuncs["dje_ne"] = func() locales.Translator { return dje_NE.New() }
translatorFuncs["dsb"] = func() locales.Translator { return dsb.New() }
translatorFuncs["dsb_de"] = func() locales.Translator { return dsb_DE.New() }
translatorFuncs["dua"] = func() locales.Translator { return dua.New() }
translatorFuncs["dua_cm"] = func() locales.Translator { return dua_CM.New() }
translatorFuncs["dyo"] = func() locales.Translator { return dyo.New() }
translatorFuncs["dyo_sn"] = func() locales.Translator { return dyo_SN.New() }
translatorFuncs["dz"] = func() locales.Translator { return dz.New() }
translatorFuncs["dz_bt"] = func() locales.Translator { return dz_BT.New() }
translatorFuncs["ebu"] = func() locales.Translator { return ebu.New() }
translatorFuncs["ebu_ke"] = func() locales.Translator { return ebu_KE.New() }
translatorFuncs["ee"] = func() locales.Translator { return ee.New() }
translatorFuncs["ee_gh"] = func() locales.Translator { return ee_GH.New() }
translatorFuncs["ee_tg"] = func() locales.Translator { return ee_TG.New() }
translatorFuncs["el"] = func() locales.Translator { return el.New() }
translatorFuncs["el_cy"] = func() locales.Translator { return el_CY.New() }
translatorFuncs["el_gr"] = func() locales.Translator { return el_GR.New() }
translatorFuncs["en"] = func() locales.Translator { return en.New() }
translatorFuncs["en_001"] = func() locales.Translator { return en_001.New() }
translatorFuncs["en_150"] = func() locales.Translator { return en_150.New() }
translatorFuncs["en_ag"] = func() locales.Translator { return en_AG.New() }
translatorFuncs["en_ai"] = func() locales.Translator { return en_AI.New() }
translatorFuncs["en_as"] = func() locales.Translator { return en_AS.New() }
translatorFuncs["en_at"] = func() locales.Translator { return en_AT.New() }
translatorFuncs["en_au"] = func() locales.Translator { return en_AU.New() }
translatorFuncs["en_bb"] = func() locales.Translator { return en_BB.New() }
translatorFuncs["en_be"] = func() locales.Translator { return en_BE.New() }
translatorFuncs["en_bi"] = func() locales.Translator { return en_BI.New() }
translatorFuncs["en_bm"] = func() locales.Translator { return en_BM.New() }
translatorFuncs["en_bs"] = func() locales.Translator { return en_BS.New() }
translatorFuncs["en_bw"] = func() locales.Translator { return en_BW.New() }
translatorFuncs["en_bz"] = func() locales.Translator { return en_BZ.New() }
translatorFuncs["en_ca"] = func() locales.Translator { return en_CA.New() }
translatorFuncs["en_cc"] = func() locales.Translator { return en_CC.New() }
translatorFuncs["en_ch"] = func() locales.Translator { return en_CH.New() }
translatorFuncs["en_ck"] = func() locales.Translator { return en_CK.New() }
translatorFuncs["en_cm"] = func() locales.Translator { return en_CM.New() }
translatorFuncs["en_cx"] = func() locales.Translator { return en_CX.New() }
translatorFuncs["en_cy"] = func() locales.Translator { return en_CY.New() }
translatorFuncs["en_de"] = func() locales.Translator { return en_DE.New() }
translatorFuncs["en_dg"] = func() locales.Translator { return en_DG.New() }
translatorFuncs["en_dk"] = func() locales.Translator { return en_DK.New() }
translatorFuncs["en_dm"] = func() locales.Translator { return en_DM.New() }
translatorFuncs["en_er"] = func() locales.Translator { return en_ER.New() }
translatorFuncs["en_fi"] = func() locales.Translator { return en_FI.New() }
translatorFuncs["en_fj"] = func() locales.Translator { return en_FJ.New() }
translatorFuncs["en_fk"] = func() locales.Translator { return en_FK.New() }
translatorFuncs["en_fm"] = func() locales.Translator { return en_FM.New() }
translatorFuncs["en_gb"] = func() locales.Translator { return en_GB.New() }
translatorFuncs["en_gd"] = func() locales.Translator { return en_GD.New() }
translatorFuncs["en_gg"] = func() locales.Translator { return en_GG.New() }
translatorFuncs["en_gh"] = func() locales.Translator { return en_GH.New() }
translatorFuncs["en_gi"] = func() locales.Translator { return en_GI.New() }
translatorFuncs["en_gm"] = func() locales.Translator { return en_GM.New() }
translatorFuncs["en_gu"] = func() locales.Translator { return en_GU.New() }
translatorFuncs["en_gy"] = func() locales.Translator { return en_GY.New() }
translatorFuncs["en_hk"] = func() locales.Translator { return en_HK.New() }
translatorFuncs["en_ie"] = func() locales.Translator { return en_IE.New() }
translatorFuncs["en_il"] = func() locales.Translator { return en_IL.New() }
translatorFuncs["en_im"] = func() locales.Translator { return en_IM.New() }
translatorFuncs["en_in"] = func() locales.Translator { return en_IN.New() }
translatorFuncs["en_io"] = func() locales.Translator { return en_IO.New() }
translatorFuncs["en_je"] = func() locales.Translator { return en_JE.New() }
translatorFuncs["en_jm"] = func() locales.Translator { return en_JM.New() }
translatorFuncs["en_ke"] = func() locales.Translator { return en_KE.New() }
translatorFuncs["en_ki"] = func() locales.Translator { return en_KI.New() }
translatorFuncs["en_kn"] = func() locales.Translator { return en_KN.New() }
translatorFuncs["en_ky"] = func() locales.Translator { return en_KY.New() }
translatorFuncs["en_lc"] = func() locales.Translator { return en_LC.New() }
translatorFuncs["en_lr"] = func() locales.Translator { return en_LR.New() }
translatorFuncs["en_ls"] = func() locales.Translator { return en_LS.New() }
translatorFuncs["en_mg"] = func() locales.Translator { return en_MG.New() }
translatorFuncs["en_mh"] = func() locales.Translator { return en_MH.New() }
translatorFuncs["en_mo"] = func() locales.Translator { return en_MO.New() }
translatorFuncs["en_mp"] = func() locales.Translator { return en_MP.New() }
translatorFuncs["en_ms"] = func() locales.Translator { return en_MS.New() }
translatorFuncs["en_mt"] = func() locales.Translator { return en_MT.New() }
translatorFuncs["en_mu"] = func() locales.Translator { return en_MU.New() }
translatorFuncs["en_mw"] = func() locales.Translator { return en_MW.New() }
translatorFuncs["en_my"] = func() locales.Translator { return en_MY.New() }
translatorFuncs["en_na"] = func() locales.Translator { return en_NA.New() }
translatorFuncs["en_nf"] = func() locales.Translator { return en_NF.New() }
translatorFuncs["en_ng"] = func() locales.Translator { return en_NG.New() }
translatorFuncs["en_nl"] = func() locales.Translator { return en_NL.New() }
translatorFuncs["en_nr"] = func() locales.Translator { return en_NR.New() }
translatorFuncs["en_nu"] = func() locales.Translator { return en_NU.New() }
translatorFuncs["en_nz"] = func() locales.Translator { return en_NZ.New() }
translatorFuncs["en_pg"] = func() locales.Translator { return en_PG.New() }
translatorFuncs["en_ph"] = func() locales.Translator { return en_PH.New() }
translatorFuncs["en_pk"] = func() locales.Translator { return en_PK.New() }
translatorFuncs["en_pn"] = func() locales.Translator { return en_PN.New() }
translatorFuncs["en_pr"] = func() locales.Translator { return en_PR.New() }
translatorFuncs["en_pw"] = func() locales.Translator { return en_PW.New() }
translatorFuncs["en_rw"] = func() locales.Translator { return en_RW.New() }
translatorFuncs["en_sb"] = func() locales.Translator { return en_SB.New() }
translatorFuncs["en_sc"] = func() locales.Translator { return en_SC.New() }
translatorFuncs["en_sd"] = func() locales.Translator { return en_SD.New() }
translatorFuncs["en_se"] = func() locales.Translator { return en_SE.New() }
translatorFuncs["en_sg"] = func() locales.Translator { return en_SG.New() }
translatorFuncs["en_sh"] = func() locales.Translator { return en_SH.New() }
translatorFuncs["en_si"] = func() locales.Translator { return en_SI.New() }
translatorFuncs["en_sl"] = func() locales.Translator { return en_SL.New() }
translatorFuncs["en_ss"] = func() locales.Translator { return en_SS.New() }
translatorFuncs["en_sx"] = func() locales.Translator { return en_SX.New() }
translatorFuncs["en_sz"] = func() locales.Translator { return en_SZ.New() }
translatorFuncs["en_tc"] = func() locales.Translator { return en_TC.New() }
translatorFuncs["en_tk"] = func() locales.Translator { return en_TK.New() }
translatorFuncs["en_to"] = func() locales.Translator { return en_TO.New() }
translatorFuncs["en_tt"] = func() locales.Translator { return en_TT.New() }
translatorFuncs["en_tv"] = func() locales.Translator { return en_TV.New() }
translatorFuncs["en_tz"] = func() locales.Translator { return en_TZ.New() }
translatorFuncs["en_ug"] = func() locales.Translator { return en_UG.New() }
translatorFuncs["en_um"] = func() locales.Translator { return en_UM.New() }
translatorFuncs["en_us"] = func() locales.Translator { return en_US.New() }
translatorFuncs["en_us_posix"] = func() locales.Translator { return en_US_POSIX.New() }
translatorFuncs["en_vc"] = func() locales.Translator { return en_VC.New() }
translatorFuncs["en_vg"] = func() locales.Translator { return en_VG.New() }
translatorFuncs["en_vi"] = func() locales.Translator { return en_VI.New() }
translatorFuncs["en_vu"] = func() locales.Translator { return en_VU.New() }
translatorFuncs["en_ws"] = func() locales.Translator { return en_WS.New() }
translatorFuncs["en_za"] = func() locales.Translator { return en_ZA.New() }
translatorFuncs["en_zm"] = func() locales.Translator { return en_ZM.New() }
translatorFuncs["en_zw"] = func() locales.Translator { return en_ZW.New() }
translatorFuncs["eo"] = func() locales.Translator { return eo.New() }
translatorFuncs["eo_001"] = func() locales.Translator { return eo_001.New() }
translatorFuncs["es"] = func() locales.Translator { return es.New() }
translatorFuncs["es_419"] = func() locales.Translator { return es_419.New() }
translatorFuncs["es_ar"] = func() locales.Translator { return es_AR.New() }
translatorFuncs["es_bo"] = func() locales.Translator { return es_BO.New() }
translatorFuncs["es_br"] = func() locales.Translator { return es_BR.New() }
translatorFuncs["es_bz"] = func() locales.Translator { return es_BZ.New() }
translatorFuncs["es_cl"] = func() locales.Translator { return es_CL.New() }
translatorFuncs["es_co"] = func() locales.Translator { return es_CO.New() }
translatorFuncs["es_cr"] = func() locales.Translator { return es_CR.New() }
translatorFuncs["es_cu"] = func() locales.Translator { return es_CU.New() }
translatorFuncs["es_do"] = func() locales.Translator { return es_DO.New() }
translatorFuncs["es_ea"] = func() locales.Translator { return es_EA.New() }
translatorFuncs["es_ec"] = func() locales.Translator { return es_EC.New() }
translatorFuncs["es_es"] = func() locales.Translator { return es_ES.New() }
translatorFuncs["es_gq"] = func() locales.Translator { return es_GQ.New() }
translatorFuncs["es_gt"] = func() locales.Translator { return es_GT.New() }
translatorFuncs["es_hn"] = func() locales.Translator { return es_HN.New() }
translatorFuncs["es_ic"] = func() locales.Translator { return es_IC.New() }
translatorFuncs["es_mx"] = func() locales.Translator { return es_MX.New() }
translatorFuncs["es_ni"] = func() locales.Translator { return es_NI.New() }
translatorFuncs["es_pa"] = func() locales.Translator { return es_PA.New() }
translatorFuncs["es_pe"] = func() locales.Translator { return es_PE.New() }
translatorFuncs["es_ph"] = func() locales.Translator { return es_PH.New() }
translatorFuncs["es_pr"] = func() locales.Translator { return es_PR.New() }
translatorFuncs["es_py"] = func() locales.Translator { return es_PY.New() }
translatorFuncs["es_sv"] = func() locales.Translator { return es_SV.New() }
translatorFuncs["es_us"] = func() locales.Translator { return es_US.New() }
translatorFuncs["es_uy"] = func() locales.Translator { return es_UY.New() }
translatorFuncs["es_ve"] = func() locales.Translator { return es_VE.New() }
translatorFuncs["et"] = func() locales.Translator { return et.New() }
translatorFuncs["et_ee"] = func() locales.Translator { return et_EE.New() }
translatorFuncs["eu"] = func() locales.Translator { return eu.New() }
translatorFuncs["eu_es"] = func() locales.Translator { return eu_ES.New() }
translatorFuncs["ewo"] = func() locales.Translator { return ewo.New() }
translatorFuncs["ewo_cm"] = func() locales.Translator { return ewo_CM.New() }
translatorFuncs["fa"] = func() locales.Translator { return fa.New() }
translatorFuncs["fa_af"] = func() locales.Translator { return fa_AF.New() }
translatorFuncs["fa_ir"] = func() locales.Translator { return fa_IR.New() }
translatorFuncs["ff"] = func() locales.Translator { return ff.New() }
translatorFuncs["ff_cm"] = func() locales.Translator { return ff_CM.New() }
translatorFuncs["ff_gn"] = func() locales.Translator { return ff_GN.New() }
translatorFuncs["ff_mr"] = func() locales.Translator { return ff_MR.New() }
translatorFuncs["ff_sn"] = func() locales.Translator { return ff_SN.New() }
translatorFuncs["fi"] = func() locales.Translator { return fi.New() }
translatorFuncs["fi_fi"] = func() locales.Translator { return fi_FI.New() }
translatorFuncs["fil"] = func() locales.Translator { return fil.New() }
translatorFuncs["fil_ph"] = func() locales.Translator { return fil_PH.New() }
translatorFuncs["fo"] = func() locales.Translator { return fo.New() }
translatorFuncs["fo_dk"] = func() locales.Translator { return fo_DK.New() }
translatorFuncs["fo_fo"] = func() locales.Translator { return fo_FO.New() }
translatorFuncs["fr"] = func() locales.Translator { return fr.New() }
translatorFuncs["fr_be"] = func() locales.Translator { return fr_BE.New() }
translatorFuncs["fr_bf"] = func() locales.Translator { return fr_BF.New() }
translatorFuncs["fr_bi"] = func() locales.Translator { return fr_BI.New() }
translatorFuncs["fr_bj"] = func() locales.Translator { return fr_BJ.New() }
translatorFuncs["fr_bl"] = func() locales.Translator { return fr_BL.New() }
translatorFuncs["fr_ca"] = func() locales.Translator { return fr_CA.New() }
translatorFuncs["fr_cd"] = func() locales.Translator { return fr_CD.New() }
translatorFuncs["fr_cf"] = func() locales.Translator { return fr_CF.New() }
translatorFuncs["fr_cg"] = func() locales.Translator { return fr_CG.New() }
translatorFuncs["fr_ch"] = func() locales.Translator { return fr_CH.New() }
translatorFuncs["fr_ci"] = func() locales.Translator { return fr_CI.New() }
translatorFuncs["fr_cm"] = func() locales.Translator { return fr_CM.New() }
translatorFuncs["fr_dj"] = func() locales.Translator { return fr_DJ.New() }
translatorFuncs["fr_dz"] = func() locales.Translator { return fr_DZ.New() }
translatorFuncs["fr_fr"] = func() locales.Translator { return fr_FR.New() }
translatorFuncs["fr_ga"] = func() locales.Translator { return fr_GA.New() }
translatorFuncs["fr_gf"] = func() locales.Translator { return fr_GF.New() }
translatorFuncs["fr_gn"] = func() locales.Translator { return fr_GN.New() }
translatorFuncs["fr_gp"] = func() locales.Translator { return fr_GP.New() }
translatorFuncs["fr_gq"] = func() locales.Translator { return fr_GQ.New() }
translatorFuncs["fr_ht"] = func() locales.Translator { return fr_HT.New() }
translatorFuncs["fr_km"] = func() locales.Translator { return fr_KM.New() }
translatorFuncs["fr_lu"] = func() locales.Translator { return fr_LU.New() }
translatorFuncs["fr_ma"] = func() locales.Translator { return fr_MA.New() }
translatorFuncs["fr_mc"] = func() locales.Translator { return fr_MC.New() }
translatorFuncs["fr_mf"] = func() locales.Translator { return fr_MF.New() }
translatorFuncs["fr_mg"] = func() locales.Translator { return fr_MG.New() }
translatorFuncs["fr_ml"] = func() locales.Translator { return fr_ML.New() }
translatorFuncs["fr_mq"] = func() locales.Translator { return fr_MQ.New() }
translatorFuncs["fr_mr"] = func() locales.Translator { return fr_MR.New() }
translatorFuncs["fr_mu"] = func() locales.Translator { return fr_MU.New() }
translatorFuncs["fr_nc"] = func() locales.Translator { return fr_NC.New() }
translatorFuncs["fr_ne"] = func() locales.Translator { return fr_NE.New() }
translatorFuncs["fr_pf"] = func() locales.Translator { return fr_PF.New() }
translatorFuncs["fr_pm"] = func() locales.Translator { return fr_PM.New() }
translatorFuncs["fr_re"] = func() locales.Translator { return fr_RE.New() }
translatorFuncs["fr_rw"] = func() locales.Translator { return fr_RW.New() }
translatorFuncs["fr_sc"] = func() locales.Translator { return fr_SC.New() }
translatorFuncs["fr_sn"] = func() locales.Translator { return fr_SN.New() }
translatorFuncs["fr_sy"] = func() locales.Translator { return fr_SY.New() }
translatorFuncs["fr_td"] = func() locales.Translator { return fr_TD.New() }
translatorFuncs["fr_tg"] = func() locales.Translator { return fr_TG.New() }
translatorFuncs["fr_tn"] = func() locales.Translator { return fr_TN.New() }
translatorFuncs["fr_vu"] = func() locales.Translator { return fr_VU.New() }
translatorFuncs["fr_wf"] = func() locales.Translator { return fr_WF.New() }
translatorFuncs["fr_yt"] = func() locales.Translator { return fr_YT.New() }
translatorFuncs["fur"] = func() locales.Translator { return fur.New() }
translatorFuncs["fur_it"] = func() locales.Translator { return fur_IT.New() }
translatorFuncs["fy"] = func() locales.Translator { return fy.New() }
translatorFuncs["fy_nl"] = func() locales.Translator { return fy_NL.New() }
translatorFuncs["ga"] = func() locales.Translator { return ga.New() }
translatorFuncs["ga_ie"] = func() locales.Translator { return ga_IE.New() }
translatorFuncs["gd"] = func() locales.Translator { return gd.New() }
translatorFuncs["gd_gb"] = func() locales.Translator { return gd_GB.New() }
translatorFuncs["gl"] = func() locales.Translator { return gl.New() }
translatorFuncs["gl_es"] = func() locales.Translator { return gl_ES.New() }
translatorFuncs["gsw"] = func() locales.Translator { return gsw.New() }
translatorFuncs["gsw_ch"] = func() locales.Translator { return gsw_CH.New() }
translatorFuncs["gsw_fr"] = func() locales.Translator { return gsw_FR.New() }
translatorFuncs["gsw_li"] = func() locales.Translator { return gsw_LI.New() }
translatorFuncs["gu"] = func() locales.Translator { return gu.New() }
translatorFuncs["gu_in"] = func() locales.Translator { return gu_IN.New() }
translatorFuncs["guz"] = func() locales.Translator { return guz.New() }
translatorFuncs["guz_ke"] = func() locales.Translator { return guz_KE.New() }
translatorFuncs["gv"] = func() locales.Translator { return gv.New() }
translatorFuncs["gv_im"] = func() locales.Translator { return gv_IM.New() }
translatorFuncs["ha"] = func() locales.Translator { return ha.New() }
translatorFuncs["ha_gh"] = func() locales.Translator { return ha_GH.New() }
translatorFuncs["ha_ne"] = func() locales.Translator { return ha_NE.New() }
translatorFuncs["ha_ng"] = func() locales.Translator { return ha_NG.New() }
translatorFuncs["haw"] = func() locales.Translator { return haw.New() }
translatorFuncs["haw_us"] = func() locales.Translator { return haw_US.New() }
translatorFuncs["he"] = func() locales.Translator { return he.New() }
translatorFuncs["he_il"] = func() locales.Translator { return he_IL.New() }
translatorFuncs["hi"] = func() locales.Translator { return hi.New() }
translatorFuncs["hi_in"] = func() locales.Translator { return hi_IN.New() }
translatorFuncs["hr"] = func() locales.Translator { return hr.New() }
translatorFuncs["hr_ba"] = func() locales.Translator { return hr_BA.New() }
translatorFuncs["hr_hr"] = func() locales.Translator { return hr_HR.New() }
translatorFuncs["hsb"] = func() locales.Translator { return hsb.New() }
translatorFuncs["hsb_de"] = func() locales.Translator { return hsb_DE.New() }
translatorFuncs["hu"] = func() locales.Translator { return hu.New() }
translatorFuncs["hu_hu"] = func() locales.Translator { return hu_HU.New() }
translatorFuncs["hy"] = func() locales.Translator { return hy.New() }
translatorFuncs["hy_am"] = func() locales.Translator { return hy_AM.New() }
translatorFuncs["id"] = func() locales.Translator { return id.New() }
translatorFuncs["id_id"] = func() locales.Translator { return id_ID.New() }
translatorFuncs["ig"] = func() locales.Translator { return ig.New() }
translatorFuncs["ig_ng"] = func() locales.Translator { return ig_NG.New() }
translatorFuncs["ii"] = func() locales.Translator { return ii.New() }
translatorFuncs["ii_cn"] = func() locales.Translator { return ii_CN.New() }
translatorFuncs["is"] = func() locales.Translator { return is.New() }
translatorFuncs["is_is"] = func() locales.Translator { return is_IS.New() }
translatorFuncs["it"] = func() locales.Translator { return it.New() }
translatorFuncs["it_ch"] = func() locales.Translator { return it_CH.New() }
translatorFuncs["it_it"] = func() locales.Translator { return it_IT.New() }
translatorFuncs["it_sm"] = func() locales.Translator { return it_SM.New() }
translatorFuncs["it_va"] = func() locales.Translator { return it_VA.New() }
translatorFuncs["ja"] = func() locales.Translator { return ja.New() }
translatorFuncs["ja_jp"] = func() locales.Translator { return ja_JP.New() }
translatorFuncs["jgo"] = func() locales.Translator { return jgo.New() }
translatorFuncs["jgo_cm"] = func() locales.Translator { return jgo_CM.New() }
translatorFuncs["jmc"] = func() locales.Translator { return jmc.New() }
translatorFuncs["jmc_tz"] = func() locales.Translator { return jmc_TZ.New() }
translatorFuncs["ka"] = func() locales.Translator { return ka.New() }
translatorFuncs["ka_ge"] = func() locales.Translator { return ka_GE.New() }
translatorFuncs["kab"] = func() locales.Translator { return kab.New() }
translatorFuncs["kab_dz"] = func() locales.Translator { return kab_DZ.New() }
translatorFuncs["kam"] = func() locales.Translator { return kam.New() }
translatorFuncs["kam_ke"] = func() locales.Translator { return kam_KE.New() }
translatorFuncs["kde"] = func() locales.Translator { return kde.New() }
translatorFuncs["kde_tz"] = func() locales.Translator { return kde_TZ.New() }
translatorFuncs["kea"] = func() locales.Translator { return kea.New() }
translatorFuncs["kea_cv"] = func() locales.Translator { return kea_CV.New() }
translatorFuncs["khq"] = func() locales.Translator { return khq.New() }
translatorFuncs["khq_ml"] = func() locales.Translator { return khq_ML.New() }
translatorFuncs["ki"] = func() locales.Translator { return ki.New() }
translatorFuncs["ki_ke"] = func() locales.Translator { return ki_KE.New() }
translatorFuncs["kk"] = func() locales.Translator { return kk.New() }
translatorFuncs["kk_kz"] = func() locales.Translator { return kk_KZ.New() }
translatorFuncs["kkj"] = func() locales.Translator { return kkj.New() }
translatorFuncs["kkj_cm"] = func() locales.Translator { return kkj_CM.New() }
translatorFuncs["kl"] = func() locales.Translator { return kl.New() }
translatorFuncs["kl_gl"] = func() locales.Translator { return kl_GL.New() }
translatorFuncs["kln"] = func() locales.Translator { return kln.New() }
translatorFuncs["kln_ke"] = func() locales.Translator { return kln_KE.New() }
translatorFuncs["km"] = func() locales.Translator { return km.New() }
translatorFuncs["km_kh"] = func() locales.Translator { return km_KH.New() }
translatorFuncs["kn"] = func() locales.Translator { return kn.New() }
translatorFuncs["kn_in"] = func() locales.Translator { return kn_IN.New() }
translatorFuncs["ko"] = func() locales.Translator { return ko.New() }
translatorFuncs["ko_kp"] = func() locales.Translator { return ko_KP.New() }
translatorFuncs["ko_kr"] = func() locales.Translator { return ko_KR.New() }
translatorFuncs["kok"] = func() locales.Translator { return kok.New() }
translatorFuncs["kok_in"] = func() locales.Translator { return kok_IN.New() }
translatorFuncs["ks"] = func() locales.Translator { return ks.New() }
translatorFuncs["ks_in"] = func() locales.Translator { return ks_IN.New() }
translatorFuncs["ksb"] = func() locales.Translator { return ksb.New() }
translatorFuncs["ksb_tz"] = func() locales.Translator { return ksb_TZ.New() }
translatorFuncs["ksf"] = func() locales.Translator { return ksf.New() }
translatorFuncs["ksf_cm"] = func() locales.Translator { return ksf_CM.New() }
translatorFuncs["ksh"] = func() locales.Translator { return ksh.New() }
translatorFuncs["ksh_de"] = func() locales.Translator { return ksh_DE.New() }
translatorFuncs["kw"] = func() locales.Translator { return kw.New() }
translatorFuncs["kw_gb"] = func() locales.Translator { return kw_GB.New() }
translatorFuncs["ky"] = func() locales.Translator { return ky.New() }
translatorFuncs["ky_kg"] = func() locales.Translator { return ky_KG.New() }
translatorFuncs["lag"] = func() locales.Translator { return lag.New() }
translatorFuncs["lag_tz"] = func() locales.Translator { return lag_TZ.New() }
translatorFuncs["lb"] = func() locales.Translator { return lb.New() }
translatorFuncs["lb_lu"] = func() locales.Translator { return lb_LU.New() }
translatorFuncs["lg"] = func() locales.Translator { return lg.New() }
translatorFuncs["lg_ug"] = func() locales.Translator { return lg_UG.New() }
translatorFuncs["lkt"] = func() locales.Translator { return lkt.New() }
translatorFuncs["lkt_us"] = func() locales.Translator { return lkt_US.New() }
translatorFuncs["ln"] = func() locales.Translator { return ln.New() }
translatorFuncs["ln_ao"] = func() locales.Translator { return ln_AO.New() }
translatorFuncs["ln_cd"] = func() locales.Translator { return ln_CD.New() }
translatorFuncs["ln_cf"] = func() locales.Translator { return ln_CF.New() }
translatorFuncs["ln_cg"] = func() locales.Translator { return ln_CG.New() }
translatorFuncs["lo"] = func() locales.Translator { return lo.New() }
translatorFuncs["lo_la"] = func() locales.Translator { return lo_LA.New() }
translatorFuncs["lrc"] = func() locales.Translator { return lrc.New() }
translatorFuncs["lrc_iq"] = func() locales.Translator { return lrc_IQ.New() }
translatorFuncs["lrc_ir"] = func() locales.Translator { return lrc_IR.New() }
translatorFuncs["lt"] = func() locales.Translator { return lt.New() }
translatorFuncs["lt_lt"] = func() locales.Translator { return lt_LT.New() }
translatorFuncs["lu"] = func() locales.Translator { return lu.New() }
translatorFuncs["lu_cd"] = func() locales.Translator { return lu_CD.New() }
translatorFuncs["luo"] = func() locales.Translator { return luo.New() }
translatorFuncs["luo_ke"] = func() locales.Translator { return luo_KE.New() }
translatorFuncs["luy"] = func() locales.Translator { return luy.New() }
translatorFuncs["luy_ke"] = func() locales.Translator { return luy_KE.New() }
translatorFuncs["lv"] = func() locales.Translator { return lv.New() }
translatorFuncs["lv_lv"] = func() locales.Translator { return lv_LV.New() }
translatorFuncs["mas"] = func() locales.Translator { return mas.New() }
translatorFuncs["mas_ke"] = func() locales.Translator { return mas_KE.New() }
translatorFuncs["mas_tz"] = func() locales.Translator { return mas_TZ.New() }
translatorFuncs["mer"] = func() locales.Translator { return mer.New() }
translatorFuncs["mer_ke"] = func() locales.Translator { return mer_KE.New() }
translatorFuncs["mfe"] = func() locales.Translator { return mfe.New() }
translatorFuncs["mfe_mu"] = func() locales.Translator { return mfe_MU.New() }
translatorFuncs["mg"] = func() locales.Translator { return mg.New() }
translatorFuncs["mg_mg"] = func() locales.Translator { return mg_MG.New() }
translatorFuncs["mgh"] = func() locales.Translator { return mgh.New() }
translatorFuncs["mgh_mz"] = func() locales.Translator { return mgh_MZ.New() }
translatorFuncs["mgo"] = func() locales.Translator { return mgo.New() }
translatorFuncs["mgo_cm"] = func() locales.Translator { return mgo_CM.New() }
translatorFuncs["mk"] = func() locales.Translator { return mk.New() }
translatorFuncs["mk_mk"] = func() locales.Translator { return mk_MK.New() }
translatorFuncs["ml"] = func() locales.Translator { return ml.New() }
translatorFuncs["ml_in"] = func() locales.Translator { return ml_IN.New() }
translatorFuncs["mn"] = func() locales.Translator { return mn.New() }
translatorFuncs["mn_mn"] = func() locales.Translator { return mn_MN.New() }
translatorFuncs["mr"] = func() locales.Translator { return mr.New() }
translatorFuncs["mr_in"] = func() locales.Translator { return mr_IN.New() }
translatorFuncs["ms"] = func() locales.Translator { return ms.New() }
translatorFuncs["ms_bn"] = func() locales.Translator { return ms_BN.New() }
translatorFuncs["ms_my"] = func() locales.Translator { return ms_MY.New() }
translatorFuncs["ms_sg"] = func() locales.Translator { return ms_SG.New() }
translatorFuncs["mt"] = func() locales.Translator { return mt.New() }
translatorFuncs["mt_mt"] = func() locales.Translator { return mt_MT.New() }
translatorFuncs["mua"] = func() locales.Translator { return mua.New() }
translatorFuncs["mua_cm"] = func() locales.Translator { return mua_CM.New() }
translatorFuncs["my"] = func() locales.Translator { return my.New() }
translatorFuncs["my_mm"] = func() locales.Translator { return my_MM.New() }
translatorFuncs["mzn"] = func() locales.Translator { return mzn.New() }
translatorFuncs["mzn_ir"] = func() locales.Translator { return mzn_IR.New() }
translatorFuncs["naq"] = func() locales.Translator { return naq.New() }
translatorFuncs["naq_na"] = func() locales.Translator { return naq_NA.New() }
translatorFuncs["nb"] = func() locales.Translator { return nb.New() }
translatorFuncs["nb_no"] = func() locales.Translator { return nb_NO.New() }
translatorFuncs["nb_sj"] = func() locales.Translator { return nb_SJ.New() }
translatorFuncs["nd"] = func() locales.Translator { return nd.New() }
translatorFuncs["nd_zw"] = func() locales.Translator { return nd_ZW.New() }
translatorFuncs["nds"] = func() locales.Translator { return nds.New() }
translatorFuncs["nds_de"] = func() locales.Translator { return nds_DE.New() }
translatorFuncs["nds_nl"] = func() locales.Translator { return nds_NL.New() }
translatorFuncs["ne"] = func() locales.Translator { return ne.New() }
translatorFuncs["ne_in"] = func() locales.Translator { return ne_IN.New() }
translatorFuncs["ne_np"] = func() locales.Translator { return ne_NP.New() }
translatorFuncs["nl"] = func() locales.Translator { return nl.New() }
translatorFuncs["nl_aw"] = func() locales.Translator { return nl_AW.New() }
translatorFuncs["nl_be"] = func() locales.Translator { return nl_BE.New() }
translatorFuncs["nl_bq"] = func() locales.Translator { return nl_BQ.New() }
translatorFuncs["nl_cw"] = func() locales.Translator { return nl_CW.New() }
translatorFuncs["nl_nl"] = func() locales.Translator { return nl_NL.New() }
translatorFuncs["nl_sr"] = func() locales.Translator { return nl_SR.New() }
translatorFuncs["nl_sx"] = func() locales.Translator { return nl_SX.New() }
translatorFuncs["nmg"] = func() locales.Translator { return nmg.New() }
translatorFuncs["nmg_cm"] = func() locales.Translator { return nmg_CM.New() }
translatorFuncs["nn"] = func() locales.Translator { return nn.New() }
translatorFuncs["nn_no"] = func() locales.Translator { return nn_NO.New() }
translatorFuncs["nnh"] = func() locales.Translator { return nnh.New() }
translatorFuncs["nnh_cm"] = func() locales.Translator { return nnh_CM.New() }
translatorFuncs["nus"] = func() locales.Translator { return nus.New() }
translatorFuncs["nus_ss"] = func() locales.Translator { return nus_SS.New() }
translatorFuncs["nyn"] = func() locales.Translator { return nyn.New() }
translatorFuncs["nyn_ug"] = func() locales.Translator { return nyn_UG.New() }
translatorFuncs["om"] = func() locales.Translator { return om.New() }
translatorFuncs["om_et"] = func() locales.Translator { return om_ET.New() }
translatorFuncs["om_ke"] = func() locales.Translator { return om_KE.New() }
translatorFuncs["or"] = func() locales.Translator { return or.New() }
translatorFuncs["or_in"] = func() locales.Translator { return or_IN.New() }
translatorFuncs["os"] = func() locales.Translator { return os.New() }
translatorFuncs["os_ge"] = func() locales.Translator { return os_GE.New() }
translatorFuncs["os_ru"] = func() locales.Translator { return os_RU.New() }
translatorFuncs["pa"] = func() locales.Translator { return pa.New() }
translatorFuncs["pa_arab"] = func() locales.Translator { return pa_Arab.New() }
translatorFuncs["pa_arab_pk"] = func() locales.Translator { return pa_Arab_PK.New() }
translatorFuncs["pa_guru"] = func() locales.Translator { return pa_Guru.New() }
translatorFuncs["pa_guru_in"] = func() locales.Translator { return pa_Guru_IN.New() }
translatorFuncs["pl"] = func() locales.Translator { return pl.New() }
translatorFuncs["pl_pl"] = func() locales.Translator { return pl_PL.New() }
translatorFuncs["prg"] = func() locales.Translator { return prg.New() }
translatorFuncs["prg_001"] = func() locales.Translator { return prg_001.New() }
translatorFuncs["ps"] = func() locales.Translator { return ps.New() }
translatorFuncs["ps_af"] = func() locales.Translator { return ps_AF.New() }
translatorFuncs["pt"] = func() locales.Translator { return pt.New() }
translatorFuncs["pt_ao"] = func() locales.Translator { return pt_AO.New() }
translatorFuncs["pt_br"] = func() locales.Translator { return pt_BR.New() }
translatorFuncs["pt_ch"] = func() locales.Translator { return pt_CH.New() }
translatorFuncs["pt_cv"] = func() locales.Translator { return pt_CV.New() }
translatorFuncs["pt_gq"] = func() locales.Translator { return pt_GQ.New() }
translatorFuncs["pt_gw"] = func() locales.Translator { return pt_GW.New() }
translatorFuncs["pt_lu"] = func() locales.Translator { return pt_LU.New() }
translatorFuncs["pt_mo"] = func() locales.Translator { return pt_MO.New() }
translatorFuncs["pt_mz"] = func() locales.Translator { return pt_MZ.New() }
translatorFuncs["pt_pt"] = func() locales.Translator { return pt_PT.New() }
translatorFuncs["pt_st"] = func() locales.Translator { return pt_ST.New() }
translatorFuncs["pt_tl"] = func() locales.Translator { return pt_TL.New() }
translatorFuncs["qu"] = func() locales.Translator { return qu.New() }
translatorFuncs["qu_bo"] = func() locales.Translator { return qu_BO.New() }
translatorFuncs["qu_ec"] = func() locales.Translator { return qu_EC.New() }
translatorFuncs["qu_pe"] = func() locales.Translator { return qu_PE.New() }
translatorFuncs["rm"] = func() locales.Translator { return rm.New() }
translatorFuncs["rm_ch"] = func() locales.Translator { return rm_CH.New() }
translatorFuncs["rn"] = func() locales.Translator { return rn.New() }
translatorFuncs["rn_bi"] = func() locales.Translator { return rn_BI.New() }
translatorFuncs["ro"] = func() locales.Translator { return ro.New() }
translatorFuncs["ro_md"] = func() locales.Translator { return ro_MD.New() }
translatorFuncs["ro_ro"] = func() locales.Translator { return ro_RO.New() }
translatorFuncs["rof"] = func() locales.Translator { return rof.New() }
translatorFuncs["rof_tz"] = func() locales.Translator { return rof_TZ.New() }
translatorFuncs["root"] = func() locales.Translator { return root.New() }
translatorFuncs["ru"] = func() locales.Translator { return ru.New() }
translatorFuncs["ru_by"] = func() locales.Translator { return ru_BY.New() }
translatorFuncs["ru_kg"] = func() locales.Translator { return ru_KG.New() }
translatorFuncs["ru_kz"] = func() locales.Translator { return ru_KZ.New() }
translatorFuncs["ru_md"] = func() locales.Translator { return ru_MD.New() }
translatorFuncs["ru_ru"] = func() locales.Translator { return ru_RU.New() }
translatorFuncs["ru_ua"] = func() locales.Translator { return ru_UA.New() }
translatorFuncs["rw"] = func() locales.Translator { return rw.New() }
translatorFuncs["rw_rw"] = func() locales.Translator { return rw_RW.New() }
translatorFuncs["rwk"] = func() locales.Translator { return rwk.New() }
translatorFuncs["rwk_tz"] = func() locales.Translator { return rwk_TZ.New() }
translatorFuncs["sah"] = func() locales.Translator { return sah.New() }
translatorFuncs["sah_ru"] = func() locales.Translator { return sah_RU.New() }
translatorFuncs["saq"] = func() locales.Translator { return saq.New() }
translatorFuncs["saq_ke"] = func() locales.Translator { return saq_KE.New() }
translatorFuncs["sbp"] = func() locales.Translator { return sbp.New() }
translatorFuncs["sbp_tz"] = func() locales.Translator { return sbp_TZ.New() }
translatorFuncs["sd"] = func() locales.Translator { return sd.New() }
translatorFuncs["sd_pk"] = func() locales.Translator { return sd_PK.New() }
translatorFuncs["se"] = func() locales.Translator { return se.New() }
translatorFuncs["se_fi"] = func() locales.Translator { return se_FI.New() }
translatorFuncs["se_no"] = func() locales.Translator { return se_NO.New() }
translatorFuncs["se_se"] = func() locales.Translator { return se_SE.New() }
translatorFuncs["seh"] = func() locales.Translator { return seh.New() }
translatorFuncs["seh_mz"] = func() locales.Translator { return seh_MZ.New() }
translatorFuncs["ses"] = func() locales.Translator { return ses.New() }
translatorFuncs["ses_ml"] = func() locales.Translator { return ses_ML.New() }
translatorFuncs["sg"] = func() locales.Translator { return sg.New() }
translatorFuncs["sg_cf"] = func() locales.Translator { return sg_CF.New() }
translatorFuncs["shi"] = func() locales.Translator { return shi.New() }
translatorFuncs["shi_latn"] = func() locales.Translator { return shi_Latn.New() }
translatorFuncs["shi_latn_ma"] = func() locales.Translator { return shi_Latn_MA.New() }
translatorFuncs["shi_tfng"] = func() locales.Translator { return shi_Tfng.New() }
translatorFuncs["shi_tfng_ma"] = func() locales.Translator { return shi_Tfng_MA.New() }
translatorFuncs["si"] = func() locales.Translator { return si.New() }
translatorFuncs["si_lk"] = func() locales.Translator { return si_LK.New() }
translatorFuncs["sk"] = func() locales.Translator { return sk.New() }
translatorFuncs["sk_sk"] = func() locales.Translator { return sk_SK.New() }
translatorFuncs["sl"] = func() locales.Translator { return sl.New() }
translatorFuncs["sl_si"] = func() locales.Translator { return sl_SI.New() }
translatorFuncs["smn"] = func() locales.Translator { return smn.New() }
translatorFuncs["smn_fi"] = func() locales.Translator { return smn_FI.New() }
translatorFuncs["sn"] = func() locales.Translator { return sn.New() }
translatorFuncs["sn_zw"] = func() locales.Translator { return sn_ZW.New() }
translatorFuncs["so"] = func() locales.Translator { return so.New() }
translatorFuncs["so_dj"] = func() locales.Translator { return so_DJ.New() }
translatorFuncs["so_et"] = func() locales.Translator { return so_ET.New() }
translatorFuncs["so_ke"] = func() locales.Translator { return so_KE.New() }
translatorFuncs["so_so"] = func() locales.Translator { return so_SO.New() }
translatorFuncs["sq"] = func() locales.Translator { return sq.New() }
translatorFuncs["sq_al"] = func() locales.Translator { return sq_AL.New() }
translatorFuncs["sq_mk"] = func() locales.Translator { return sq_MK.New() }
translatorFuncs["sq_xk"] = func() locales.Translator { return sq_XK.New() }
translatorFuncs["sr"] = func() locales.Translator { return sr.New() }
translatorFuncs["sr_cyrl"] = func() locales.Translator { return sr_Cyrl.New() }
translatorFuncs["sr_cyrl_ba"] = func() locales.Translator { return sr_Cyrl_BA.New() }
translatorFuncs["sr_cyrl_me"] = func() locales.Translator { return sr_Cyrl_ME.New() }
translatorFuncs["sr_cyrl_rs"] = func() locales.Translator { return sr_Cyrl_RS.New() }
translatorFuncs["sr_cyrl_xk"] = func() locales.Translator { return sr_Cyrl_XK.New() }
translatorFuncs["sr_latn"] = func() locales.Translator { return sr_Latn.New() }
translatorFuncs["sr_latn_ba"] = func() locales.Translator { return sr_Latn_BA.New() }
translatorFuncs["sr_latn_me"] = func() locales.Translator { return sr_Latn_ME.New() }
translatorFuncs["sr_latn_rs"] = func() locales.Translator { return sr_Latn_RS.New() }
translatorFuncs["sr_latn_xk"] = func() locales.Translator { return sr_Latn_XK.New() }
translatorFuncs["sv"] = func() locales.Translator { return sv.New() }
translatorFuncs["sv_ax"] = func() locales.Translator { return sv_AX.New() }
translatorFuncs["sv_fi"] = func() locales.Translator { return sv_FI.New() }
translatorFuncs["sv_se"] = func() locales.Translator { return sv_SE.New() }
translatorFuncs["sw"] = func() locales.Translator { return sw.New() }
translatorFuncs["sw_cd"] = func() locales.Translator { return sw_CD.New() }
translatorFuncs["sw_ke"] = func() locales.Translator { return sw_KE.New() }
translatorFuncs["sw_tz"] = func() locales.Translator { return sw_TZ.New() }
translatorFuncs["sw_ug"] = func() locales.Translator { return sw_UG.New() }
translatorFuncs["ta"] = func() locales.Translator { return ta.New() }
translatorFuncs["ta_in"] = func() locales.Translator { return ta_IN.New() }
translatorFuncs["ta_lk"] = func() locales.Translator { return ta_LK.New() }
translatorFuncs["ta_my"] = func() locales.Translator { return ta_MY.New() }
translatorFuncs["ta_sg"] = func() locales.Translator { return ta_SG.New() }
translatorFuncs["te"] = func() locales.Translator { return te.New() }
translatorFuncs["te_in"] = func() locales.Translator { return te_IN.New() }
translatorFuncs["teo"] = func() locales.Translator { return teo.New() }
translatorFuncs["teo_ke"] = func() locales.Translator { return teo_KE.New() }
translatorFuncs["teo_ug"] = func() locales.Translator { return teo_UG.New() }
translatorFuncs["tg"] = func() locales.Translator { return tg.New() }
translatorFuncs["tg_tj"] = func() locales.Translator { return tg_TJ.New() }
translatorFuncs["th"] = func() locales.Translator { return th.New() }
translatorFuncs["th_th"] = func() locales.Translator { return th_TH.New() }
translatorFuncs["ti"] = func() locales.Translator { return ti.New() }
translatorFuncs["ti_er"] = func() locales.Translator { return ti_ER.New() }
translatorFuncs["ti_et"] = func() locales.Translator { return ti_ET.New() }
translatorFuncs["tk"] = func() locales.Translator { return tk.New() }
translatorFuncs["tk_tm"] = func() locales.Translator { return tk_TM.New() }
translatorFuncs["to"] = func() locales.Translator { return to.New() }
translatorFuncs["to_to"] = func() locales.Translator { return to_TO.New() }
translatorFuncs["tr"] = func() locales.Translator { return tr.New() }
translatorFuncs["tr_cy"] = func() locales.Translator { return tr_CY.New() }
translatorFuncs["tr_tr"] = func() locales.Translator { return tr_TR.New() }
translatorFuncs["tt"] = func() locales.Translator { return tt.New() }
translatorFuncs["tt_ru"] = func() locales.Translator { return tt_RU.New() }
translatorFuncs["twq"] = func() locales.Translator { return twq.New() }
translatorFuncs["twq_ne"] = func() locales.Translator { return twq_NE.New() }
translatorFuncs["tzm"] = func() locales.Translator { return tzm.New() }
translatorFuncs["tzm_ma"] = func() locales.Translator { return tzm_MA.New() }
translatorFuncs["ug"] = func() locales.Translator { return ug.New() }
translatorFuncs["ug_cn"] = func() locales.Translator { return ug_CN.New() }
translatorFuncs["uk"] = func() locales.Translator { return uk.New() }
translatorFuncs["uk_ua"] = func() locales.Translator { return uk_UA.New() }
translatorFuncs["ur"] = func() locales.Translator { return ur.New() }
translatorFuncs["ur_in"] = func() locales.Translator { return ur_IN.New() }
translatorFuncs["ur_pk"] = func() locales.Translator { return ur_PK.New() }
translatorFuncs["uz"] = func() locales.Translator { return uz.New() }
translatorFuncs["uz_arab"] = func() locales.Translator { return uz_Arab.New() }
translatorFuncs["uz_arab_af"] = func() locales.Translator { return uz_Arab_AF.New() }
translatorFuncs["uz_cyrl"] = func() locales.Translator { return uz_Cyrl.New() }
translatorFuncs["uz_cyrl_uz"] = func() locales.Translator { return uz_Cyrl_UZ.New() }
translatorFuncs["uz_latn"] = func() locales.Translator { return uz_Latn.New() }
translatorFuncs["uz_latn_uz"] = func() locales.Translator { return uz_Latn_UZ.New() }
translatorFuncs["vai"] = func() locales.Translator { return vai.New() }
translatorFuncs["vai_latn"] = func() locales.Translator { return vai_Latn.New() }
translatorFuncs["vai_latn_lr"] = func() locales.Translator { return vai_Latn_LR.New() }
translatorFuncs["vai_vaii"] = func() locales.Translator { return vai_Vaii.New() }
translatorFuncs["vai_vaii_lr"] = func() locales.Translator { return vai_Vaii_LR.New() }
translatorFuncs["vi"] = func() locales.Translator { return vi.New() }
translatorFuncs["vi_vn"] = func() locales.Translator { return vi_VN.New() }
translatorFuncs["vo"] = func() locales.Translator { return vo.New() }
translatorFuncs["vo_001"] = func() locales.Translator { return vo_001.New() }
translatorFuncs["vun"] = func() locales.Translator { return vun.New() }
translatorFuncs["vun_tz"] = func() locales.Translator { return vun_TZ.New() }
translatorFuncs["wae"] = func() locales.Translator { return wae.New() }
translatorFuncs["wae_ch"] = func() locales.Translator { return wae_CH.New() }
translatorFuncs["wo"] = func() locales.Translator { return wo.New() }
translatorFuncs["wo_sn"] = func() locales.Translator { return wo_SN.New() }
translatorFuncs["xog"] = func() locales.Translator { return xog.New() }
translatorFuncs["xog_ug"] = func() locales.Translator { return xog_UG.New() }
translatorFuncs["yav"] = func() locales.Translator { return yav.New() }
translatorFuncs["yav_cm"] = func() locales.Translator { return yav_CM.New() }
translatorFuncs["yi"] = func() locales.Translator { return yi.New() }
translatorFuncs["yi_001"] = func() locales.Translator { return yi_001.New() }
translatorFuncs["yo"] = func() locales.Translator { return yo.New() }
translatorFuncs["yo_bj"] = func() locales.Translator { return yo_BJ.New() }
translatorFuncs["yo_ng"] = func() locales.Translator { return yo_NG.New() }
translatorFuncs["yue"] = func() locales.Translator { return yue.New() }
translatorFuncs["yue_hk"] = func() locales.Translator { return yue_HK.New() }
translatorFuncs["yue_hans"] = func() locales.Translator { return yue_Hans.New() }
translatorFuncs["yue_hans_cn"] = func() locales.Translator { return yue_Hans_CN.New() }
translatorFuncs["yue_hant"] = func() locales.Translator { return yue_Hant.New() }
translatorFuncs["yue_hant_hk"] = func() locales.Translator { return yue_Hant_HK.New() }
translatorFuncs["zgh"] = func() locales.Translator { return zgh.New() }
translatorFuncs["zgh_ma"] = func() locales.Translator { return zgh_MA.New() }
translatorFuncs["zh"] = func() locales.Translator { return zh.New() }
translatorFuncs["zh_hans"] = func() locales.Translator { return zh_Hans.New() }
translatorFuncs["zh_hans_cn"] = func() locales.Translator { return zh_Hans_CN.New() }
translatorFuncs["zh_hans_hk"] = func() locales.Translator { return zh_Hans_HK.New() }
translatorFuncs["zh_hans_mo"] = func() locales.Translator { return zh_Hans_MO.New() }
translatorFuncs["zh_hans_sg"] = func() locales.Translator { return zh_Hans_SG.New() }
translatorFuncs["zh_hant"] = func() locales.Translator { return zh_Hant.New() }
translatorFuncs["zh_hant_hk"] = func() locales.Translator { return zh_Hant_HK.New() }
translatorFuncs["zh_hant_mo"] = func() locales.Translator { return zh_Hant_MO.New() }
translatorFuncs["zh_hant_tw"] = func() locales.Translator { return zh_Hant_TW.New() }
translatorFuncs["zu"] = func() locales.Translator { return zu.New() }
translatorFuncs["zu_za"] = func() locales.Translator { return zu_ZA.New() }

}
